"""Unit tests — small, fast, real code paths only."""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
import trimesh

from hermes3d.core.design import OrganizerSpec, build_organizer, export_organizer
from hermes3d.core.validation import (
    CheckStatus,
    TruthGateConfig,
    run_truth_gate,
)


# ---------------------------------------------------------------------------
# OrganizerSpec.validated()
# ---------------------------------------------------------------------------


class TestOrganizerSpec:
    def test_default_is_valid(self) -> None:
        spec = OrganizerSpec().validated()
        assert spec.width_mm > 0 and spec.depth_mm > 0 and spec.height_mm > 0

    def test_negative_width_rejected(self) -> None:
        with pytest.raises(ValueError):
            OrganizerSpec(width_mm=-1).validated()

    def test_zero_wall_rejected(self) -> None:
        with pytest.raises(ValueError):
            OrganizerSpec(wall_mm=0).validated()

    def test_too_many_trays_rejected(self) -> None:
        # 100mm width with 2mm walls and N trays: each compartment is
        # (96 - (N-1)*2) / N. For N=50 that's negative.
        with pytest.raises(ValueError):
            build_organizer(OrganizerSpec(width_mm=100, tray_count=50))

    def test_signature_is_deterministic(self) -> None:
        a = OrganizerSpec().signature()
        b = OrganizerSpec().signature()
        assert a == b
        assert len(a) == 10

    def test_signature_changes_with_params(self) -> None:
        a = OrganizerSpec().signature()
        b = OrganizerSpec(width_mm=200).signature()
        assert a != b


# ---------------------------------------------------------------------------
# Truth Gate individual checks
# ---------------------------------------------------------------------------


def _write_box_stl(tmp: Path, name: str = "box.stl",
                  size: tuple[float, float, float] = (50, 30, 20)) -> Path:
    """Write a 50x30x20 mm watertight box STL — known good geometry."""
    box = trimesh.creation.box(extents=size)
    p = tmp / name
    box.export(str(p))
    return p


class TestTruthGate:
    def test_clean_box_passes_all_checks(self, tmp_path: Path) -> None:
        p = _write_box_stl(tmp_path)
        report = run_truth_gate(p, TruthGateConfig())
        assert report.passed, f"Clean box failed: {report.to_dict()}"
        for c in report.checks:
            # printer_fit is allowed to SKIP when no profile_id is set —
            # that's correct behaviour, not a failure.
            allowed = {CheckStatus.PASS, CheckStatus.SKIP}
            assert c.status in allowed, f"Check {c.name} failed: {c.message}"

    def test_oversize_box_fails_bed_fit(self, tmp_path: Path) -> None:
        # 300mm wide — exceeds default 220mm bed.
        p = _write_box_stl(tmp_path, "big.stl", size=(300, 30, 20))
        report = run_truth_gate(p, TruthGateConfig())
        bed_fit = next(c for c in report.checks if c.name == "bed_fit")
        assert bed_fit.status is CheckStatus.FAIL
        assert not report.passed

    def test_thin_shell_fails_thickness(self, tmp_path: Path) -> None:
        # A box with 0.5mm walls — generated by subtracting an inner box from outer.
        outer = trimesh.creation.box(extents=(20, 20, 20))
        inner = trimesh.creation.box(extents=(19, 19, 19))
        # Lift inner up so the bottom of the shell is solid.
        inner.apply_translation([0, 0, 0.5])
        shell = trimesh.boolean.difference([outer, inner], engine="manifold")
        shell.process(validate=True)
        p = tmp_path / "shell.stl"
        shell.export(str(p))
        report = run_truth_gate(p, TruthGateConfig())
        thickness = next(c for c in report.checks
                         if c.name == "wall_thickness")
        assert thickness.status is CheckStatus.FAIL
        assert thickness.measured["min_mm"] < 1.2

    def test_min_volume_check_rejects_pinheads(self, tmp_path: Path) -> None:
        tiny = trimesh.creation.box(extents=(2, 2, 2))  # 8 mm³
        p = tmp_path / "tiny.stl"
        tiny.export(str(p))
        report = run_truth_gate(p, TruthGateConfig(min_volume_mm3=100.0))
        vol = next(c for c in report.checks if c.name == "minimum_volume")
        assert vol.status is CheckStatus.FAIL

    def test_skip_flags_honoured(self, tmp_path: Path) -> None:
        p = _write_box_stl(tmp_path)
        cfg = TruthGateConfig(require_thickness=False,
                              require_no_self_intersection=False)
        report = run_truth_gate(p, cfg)
        thickness = next(c for c in report.checks if c.name == "wall_thickness")
        assert thickness.status is CheckStatus.SKIP
        si = next(c for c in report.checks if c.name == "self_intersection")
        assert si.status is CheckStatus.SKIP

    def test_report_includes_mesh_hash(self, tmp_path: Path) -> None:
        p = _write_box_stl(tmp_path)
        report = run_truth_gate(p, TruthGateConfig())
        assert len(report.mesh_sha256) == 64  # SHA-256 hex
        assert report.schema_version == "1.0.0"
