"""Post-processing script generator.

Status: runnable
Contract: 00-CONTRACT/MASTER_CONTRACT.md §45 (Post-Processing Scripts)

When the G-code analyzer or the failure predictor surfaces a known
issue, the agent can generate a Python post-processing script that
slicers like PrusaSlicer/OrcaSlicer run on the G-code before saving.

Examples of fixes the agent can inject:

  - Bump temperature 5°C from layer 50 onward (observed under-extrusion)
  - Reduce print speed by 30% in the first 10mm Z (bed adhesion issue)
  - Insert M600 filament-change at layer 87
  - Inject custom retraction sequence after every Z-hop
  - Add cooling fan ramp on overhang regions
  - Pause for spool change at specified Z

Scripts are written as standalone Python files that take the G-code
path as the only argument — exactly the contract the slicers expect.
The generator stays in pure-Python deliberately: portable, no native
deps, easy for users to inspect before running.
"""
from __future__ import annotations

import dataclasses
import enum
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# =============================================================================
# Mitigation kinds
# =============================================================================


class MitigationKind(str, enum.Enum):
    TEMP_BUMP_FROM_LAYER = "temp_bump_from_layer"
    SPEED_REDUCE_BELOW_Z = "speed_reduce_below_z"
    INSERT_PAUSE_AT_LAYER = "insert_pause_at_layer"
    INSERT_M600_AT_LAYER = "insert_m600_at_layer"
    FAN_RAMP_AT_LAYER = "fan_ramp_at_layer"
    Z_HOP_RETRACT_BOOST = "z_hop_retract_boost"


@dataclass
class Mitigation:
    kind: MitigationKind
    params: dict[str, Any] = field(default_factory=dict)
    rationale: str = ""

    def to_dict(self) -> dict[str, Any]:
        d = dataclasses.asdict(self)
        d["kind"] = self.kind.value
        return d


# =============================================================================
# Script generator
# =============================================================================


_SCRIPT_HEADER = '''#!/usr/bin/env python3
"""Post-processing script — generated by Hermes3D-OS Lite.

This script is auto-generated. It runs as the LAST step in PrusaSlicer/
OrcaSlicer, before the .gcode is saved to disk. The slicer passes the
.gcode path as argv[1].

Mitigations applied in order:
{mitigation_list}

To regenerate / modify, run the agent again with adjusted Mitigations.
Generated for: {context}
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


def _read(p: Path) -> list[str]:
    return p.read_text(encoding="utf-8").splitlines()


def _write(p: Path, lines: list[str]) -> None:
    p.write_text("\\n".join(lines) + "\\n", encoding="utf-8")


def _layer_index(line: str) -> int | None:
    """Return the layer number if this line is a layer marker."""
    m = re.match(r";LAYER:(\\d+)", line)
    if m:
        return int(m.group(1))
    m = re.match(r";LAYER_CHANGE", line)
    if m:
        return -1  # signal-only marker
    return None


def _z_value(line: str) -> float | None:
    """Return the new Z if this G0/G1 line moves Z."""
    if not line.startswith(("G0 ", "G1 ")):
        return None
    m = re.search(r"\\bZ([-\\d.]+)", line)
    return float(m.group(1)) if m else None


'''


def _emit_temp_bump(layer: int, delta_c: int, rationale: str) -> str:
    return f'''
def _mitigation_temp_bump_from_layer(lines: list[str]) -> list[str]:
    """{rationale}"""
    target_layer = {layer}
    delta_c = {delta_c}
    out: list[str] = []
    current_layer = -1
    bumped = False
    for line in lines:
        idx = _layer_index(line)
        if idx is not None and idx >= 0:
            current_layer = idx
        if current_layer >= target_layer and not bumped:
            # Find the most recent M104 / M109 to know base temperature
            base = None
            for back in reversed(out):
                m = re.match(r"M(?:104|109) (?:.*)?S(\\d+)", back)
                if m:
                    base = int(m.group(1))
                    break
            if base is not None:
                out.append(f"M104 S{{base + delta_c}}  ; hermes3d temp bump")
                bumped = True
        out.append(line)
    return out
'''


def _emit_speed_reduce(z_max_mm: float, factor: float, rationale: str) -> str:
    return f'''
def _mitigation_speed_reduce_below_z(lines: list[str]) -> list[str]:
    """{rationale}"""
    z_max = {z_max_mm}
    factor = {factor}
    out: list[str] = []
    current_z = 0.0
    for line in lines:
        nz = _z_value(line)
        if nz is not None:
            current_z = nz
        if current_z <= z_max and line.startswith(("G1 ", "G0 ")):
            # Halve any explicit feed rate
            line = re.sub(
                r"\\bF(\\d+(?:\\.\\d+)?)",
                lambda m: f"F{{float(m.group(1)) * factor:.0f}}",
                line,
            )
        out.append(line)
    return out
'''


def _emit_pause(layer: int, rationale: str) -> str:
    return f'''
def _mitigation_insert_pause_at_layer(lines: list[str]) -> list[str]:
    """{rationale}"""
    target_layer = {layer}
    out: list[str] = []
    inserted = False
    current_layer = -1
    for line in lines:
        idx = _layer_index(line)
        if idx is not None and idx >= 0:
            current_layer = idx
        if current_layer == target_layer and not inserted:
            out.append("M0 ; hermes3d pause for inspection")
            inserted = True
        out.append(line)
    return out
'''


def _emit_m600(layer: int, rationale: str) -> str:
    return f'''
def _mitigation_insert_m600_at_layer(lines: list[str]) -> list[str]:
    """{rationale}"""
    target_layer = {layer}
    out: list[str] = []
    inserted = False
    current_layer = -1
    for line in lines:
        idx = _layer_index(line)
        if idx is not None and idx >= 0:
            current_layer = idx
        if current_layer == target_layer and not inserted:
            out.append("M600 ; hermes3d filament change")
            inserted = True
        out.append(line)
    return out
'''


def _emit_fan_ramp(layer: int, target_pct: int, rationale: str) -> str:
    return f'''
def _mitigation_fan_ramp_at_layer(lines: list[str]) -> list[str]:
    """{rationale}"""
    target_layer = {layer}
    target_pct = {target_pct}
    out: list[str] = []
    inserted = False
    current_layer = -1
    target_S = int(target_pct * 255 / 100)
    for line in lines:
        idx = _layer_index(line)
        if idx is not None and idx >= 0:
            current_layer = idx
        if current_layer == target_layer and not inserted:
            out.append(f"M106 S{{target_S}} ; hermes3d fan ramp to {{target_pct}}%")
            inserted = True
        out.append(line)
    return out
'''


def _emit_retract_boost(extra_mm: float, rationale: str) -> str:
    return f'''
def _mitigation_z_hop_retract_boost(lines: list[str]) -> list[str]:
    """{rationale}"""
    extra_mm = {extra_mm}
    out: list[str] = []
    pending_retract = False
    for line in lines:
        # Detect retract: G1 with E negative, no other axes
        if re.match(r"G1 E-([\\d.]+)( F\\d+)?$", line):
            m = re.match(r"G1 E-([\\d.]+)( F\\d+)?$", line)
            base = float(m.group(1))
            f = m.group(2) or ""
            line = f"G1 E-{{base + extra_mm:.4f}}{{f}} ; hermes3d retract boost"
        out.append(line)
    return out
'''


_SCRIPT_FOOTER = '''
def main(gcode_path: str) -> int:
    p = Path(gcode_path)
    if not p.exists():
        print(f"file not found: {gcode_path}", file=sys.stderr)
        return 1
    lines = _read(p)
    for fn in _MITIGATIONS:
        lines = fn(lines)
    _write(p, lines)
    return 0


_MITIGATIONS = [{mitigation_fns}]


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else ""))
'''


@dataclass
class GeneratedScript:
    path: Path | None
    source: str
    mitigation_count: int


def generate_script(mitigations: list[Mitigation], *,
                     output_path: Path | str | None = None,
                     context: str = "(unknown)",
                     ) -> GeneratedScript:
    """Compose a runnable post-processing script from a list of mitigations.

    The slicer is configured to call:: ``python scriptpath ${{output_path}}``
    """
    bullets = "\n".join(
        f"    {i+1}. [{m.kind.value}] {m.rationale or '(no rationale)'}"
        for i, m in enumerate(mitigations)
    )
    fns: list[str] = []
    bodies: list[str] = []
    for m in mitigations:
        rationale = (m.rationale or "no rationale provided").replace(
            '"', "'")
        if m.kind is MitigationKind.TEMP_BUMP_FROM_LAYER:
            bodies.append(_emit_temp_bump(
                int(m.params["layer"]),
                int(m.params.get("delta_c", 5)),
                rationale))
            fns.append("_mitigation_temp_bump_from_layer")
        elif m.kind is MitigationKind.SPEED_REDUCE_BELOW_Z:
            bodies.append(_emit_speed_reduce(
                float(m.params.get("z_max_mm", 1.0)),
                float(m.params.get("factor", 0.5)),
                rationale))
            fns.append("_mitigation_speed_reduce_below_z")
        elif m.kind is MitigationKind.INSERT_PAUSE_AT_LAYER:
            bodies.append(_emit_pause(
                int(m.params["layer"]), rationale))
            fns.append("_mitigation_insert_pause_at_layer")
        elif m.kind is MitigationKind.INSERT_M600_AT_LAYER:
            bodies.append(_emit_m600(
                int(m.params["layer"]), rationale))
            fns.append("_mitigation_insert_m600_at_layer")
        elif m.kind is MitigationKind.FAN_RAMP_AT_LAYER:
            bodies.append(_emit_fan_ramp(
                int(m.params["layer"]),
                int(m.params.get("target_pct", 100)),
                rationale))
            fns.append("_mitigation_fan_ramp_at_layer")
        elif m.kind is MitigationKind.Z_HOP_RETRACT_BOOST:
            bodies.append(_emit_retract_boost(
                float(m.params.get("extra_mm", 0.5)),
                rationale))
            fns.append("_mitigation_z_hop_retract_boost")
        else:
            raise ValueError(f"unknown mitigation kind: {m.kind!r}")

    # De-duplicate function bodies (if the same mitigation type appears
    # twice we'd otherwise emit the function twice). We keep the first
    # occurrence for each.
    seen_fns: set[str] = set()
    unique_bodies: list[str] = []
    for fn, body in zip(fns, bodies):
        if fn in seen_fns:
            continue
        seen_fns.add(fn)
        unique_bodies.append(body)

    src = (
        _SCRIPT_HEADER.format(mitigation_list=bullets, context=context)
        + "\n".join(unique_bodies)
        + _SCRIPT_FOOTER.format(
            mitigation_fns=", ".join(fns) or "")
    )

    written: Path | None = None
    if output_path is not None:
        written = Path(output_path)
        written.parent.mkdir(parents=True, exist_ok=True)
        written.write_text(src, encoding="utf-8")
        try:
            written.chmod(0o755)
        except (OSError, NotImplementedError):
            pass
    return GeneratedScript(
        path=written, source=src, mitigation_count=len(mitigations))


__all__ = [
    "GeneratedScript",
    "Mitigation",
    "MitigationKind",
    "generate_script",
]
