"""Slicer profile generator.

Status: runnable
Contract: 00_overview/contract/MASTER_CONTRACT.md §44 (Slicer Profile Generator)

Auto-builds a working PrusaSlicer/OrcaSlicer .ini profile for any
(printer × material × quality_level) combination. The profile blends:

  - Printer metadata from `printer_profiles.py` (bed, kinematics,
    nozzle diameter, max volumetric speed, flow ratios)
  - Material metadata from `materials.py` (hot end + bed temp,
    cooling fan policy, retraction defaults)
  - Skill-store overrides — every PARAMETER_OVERRIDE skill that
    matches the (printer, material, quality) scope is applied
  - Quality presets (draft / normal / fine) tweak layer height,
    perimeter count, infill density

Output is a PrusaSlicer/OrcaSlicer-compatible .ini text file. The
caller can write it to disk and pass it to `slice_mesh(profile=...)`.

This module is the bridge between the kit's structured printer/material
data and the slicer's flat key/value config files.
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from hermes3d.core.agents.materials import MATERIALS, get_material
from hermes3d.core.memory import SkillKind, SkillStore
from hermes3d.core.printers import get_profile, PrinterProfile, Kinematics


# =============================================================================
# Quality presets
# =============================================================================


@dataclass(frozen=True)
class QualityPreset:
    name: str
    layer_height_mm: float
    first_layer_height_mm: float
    perimeters: int
    top_solid_layers: int
    bottom_solid_layers: int
    fill_density_pct: int


QUALITY_PRESETS: dict[str, QualityPreset] = {
    "draft": QualityPreset(
        name="draft",
        layer_height_mm=0.28,
        first_layer_height_mm=0.32,
        perimeters=2,
        top_solid_layers=3,
        bottom_solid_layers=3,
        fill_density_pct=15,
    ),
    "normal": QualityPreset(
        name="normal",
        layer_height_mm=0.20,
        first_layer_height_mm=0.24,
        perimeters=3,
        top_solid_layers=4,
        bottom_solid_layers=4,
        fill_density_pct=20,
    ),
    "fine": QualityPreset(
        name="fine",
        layer_height_mm=0.12,
        first_layer_height_mm=0.20,
        perimeters=4,
        top_solid_layers=5,
        bottom_solid_layers=5,
        fill_density_pct=25,
    ),
}


# =============================================================================
# Profile generation
# =============================================================================


@dataclass
class GeneratedProfile:
    profile_id: str
    printer_id: str
    material: str
    quality_level: str
    settings: dict[str, str] = field(default_factory=dict)
    applied_skills: list[str] = field(default_factory=list)

    def to_ini(self) -> str:
        """Serialize to PrusaSlicer-compatible .ini."""
        lines = [
            f"# Auto-generated by Hermes3D-OS Lite",
            f"# profile_id  = {self.profile_id}",
            f"# printer_id  = {self.printer_id}",
            f"# material    = {self.material}",
            f"# quality     = {self.quality_level}",
            "",
        ]
        if self.applied_skills:
            lines.append("# Applied skills:")
            for sk in self.applied_skills:
                lines.append(f"#   - {sk}")
            lines.append("")
        for key in sorted(self.settings):
            lines.append(f"{key} = {self.settings[key]}")
        return "\n".join(lines) + "\n"

    def write(self, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.to_ini(), encoding="utf-8")
        return p


def _bed_shape_for(profile: PrinterProfile) -> str:
    """PrusaSlicer/Orca bed_shape string."""
    bed = profile.bed
    if profile.kinematics == Kinematics.DELTA:
        # Delta: PrusaSlicer expects an octagonal approximation of the circle
        d = bed.diameter_mm or 0.0
        r = d / 2.0
        # 8-point polygon
        import math

        pts = []
        for i in range(8):
            a = i * math.pi / 4
            x, y = r * math.cos(a), r * math.sin(a)
            pts.append(f"{x:.1f}x{y:.1f}")
        return ",".join(pts)
    # Cartesian / CoreXY: rectangular bed
    w = bed.x_mm or 0.0
    h = bed.y_mm or 0.0
    return f"0x0,{w}x0,{w}x{h},0x{h}"


def generate_profile(
    *,
    printer_id: str,
    material: str,
    quality_level: str = "normal",
    skills: SkillStore | None = None,
    nozzle_diameter_mm: float = 0.4,
    filament_diameter_mm: float = 1.75,
) -> GeneratedProfile:
    """Build a slicer profile for the given combo.

    Skill overrides (when ``skills`` is provided) are applied last and
    can override any setting by writing a body like::

        body = {"slicer_setting": "first_layer_temperature", "value": 220}

    or a multi-key body::

        body = {"first_layer_temperature": 220, "fill_density": "25%"}
    """
    profile = get_profile(printer_id)
    mat = get_material(material)
    quality = QUALITY_PRESETS.get(quality_level, QUALITY_PRESETS["normal"])

    settings: dict[str, str] = {}

    # ---- Printer/bed geometry ----
    settings["printer_model"] = profile.profile_id
    settings["bed_shape"] = _bed_shape_for(profile)
    settings["max_print_height"] = str(int(profile.z_height_mm))
    settings["nozzle_diameter"] = f"{nozzle_diameter_mm}"
    settings["filament_diameter"] = f"{filament_diameter_mm}"
    settings["printer_technology"] = "FFF"

    # ---- Quality ----
    settings["layer_height"] = f"{quality.layer_height_mm}"
    settings["first_layer_height"] = f"{quality.first_layer_height_mm}"
    settings["perimeters"] = str(quality.perimeters)
    settings["top_solid_layers"] = str(quality.top_solid_layers)
    settings["bottom_solid_layers"] = str(quality.bottom_solid_layers)
    settings["fill_density"] = f"{quality.fill_density_pct}%"
    settings["fill_pattern"] = "gyroid"

    # ---- Material thermal ----
    settings["temperature"] = str(int(mat.hotend_typical_c))
    settings["first_layer_temperature"] = str(int(mat.hotend_typical_c) + 5)
    settings["bed_temperature"] = str(int(mat.bed_typical_c))
    settings["first_layer_bed_temperature"] = str(int(mat.bed_typical_c) + 5)

    # Cooling — material-specific defaults
    # PLA wants 100% fan; ABS/ASA need almost none; PETG wants moderate
    fan_pct_by_material: dict[str, int] = {
        "PLA": 100,
        "PLA+": 100,
        "CF-PLA": 80,
        "PETG": 50,
        "TPU": 80,
        "ABS": 10,
        "ASA": 15,
        "PA": 30,
        "PA-CF": 30,
        "PC": 25,
        "PVA": 40,
    }
    fan_pct = fan_pct_by_material.get(material.upper(), 60)
    settings["fan_always_on"] = "1" if fan_pct > 0 else "0"
    settings["max_fan_speed"] = str(fan_pct)
    settings["min_fan_speed"] = str(int(fan_pct * 0.5))
    settings["disable_fan_first_layers"] = "3"

    # Retraction
    settings["retract_length"] = "0.8" if profile.direct_drive else "5.0"
    settings["retract_speed"] = "30"
    settings["retract_lift"] = "0.2"

    # Speeds (deltas can run faster)
    if profile.kinematics == Kinematics.DELTA:
        settings["perimeter_speed"] = "80"
        settings["external_perimeter_speed"] = "50"
        settings["infill_speed"] = "120"
        settings["travel_speed"] = "300"
    else:
        settings["perimeter_speed"] = "50"
        settings["external_perimeter_speed"] = "30"
        settings["infill_speed"] = "80"
        settings["travel_speed"] = "180"

    # Material-specific overrides
    if mat.requires_enclosure:
        settings["chamber_temperature"] = "45"  # default — skill can override
    if material.upper() == "TPU":
        settings["retract_length"] = "0.4"
        settings["fill_density"] = f"{max(quality.fill_density_pct, 25)}%"
    if material.upper() in ("PA-CF", "CF-PLA"):
        settings["nozzle_diameter"] = "0.6"  # CF wears 0.4 nozzles fast
        settings["external_perimeter_speed"] = "20"

    # Quality-life pairings
    settings["skirts"] = "1"
    settings["skirt_distance"] = "5"
    settings["brim_width"] = "0"

    applied_skill_names: list[str] = []

    # ---- Skill overrides ----
    if skills is not None:
        matches = skills.lookup(
            kind=SkillKind.PARAMETER_OVERRIDE,
            printer_id=printer_id,
            material=material,
            quality_level=quality_level,
            min_confidence=0.4,
        )
        # Apply lowest-specificity first so most-specific wins
        for sk in sorted(matches, key=lambda s: s.scope.specificity()):
            applied_any = False
            body = sk.body or {}
            # Single-setting form
            if "slicer_setting" in body and "value" in body:
                settings[str(body["slicer_setting"])] = str(body["value"])
                applied_any = True
            else:
                # Multi-key form — every body entry maps to a setting
                for k, v in body.items():
                    if k in {"observed_failure_rate", "observation_count", "delta_c", "trigger"}:
                        continue
                    settings[str(k)] = str(v)
                    applied_any = True
            if applied_any:
                applied_skill_names.append(f"{sk.name} (conf={sk.confidence:.2f})")

    profile_id = f"hermes3d:{printer_id}:{material.lower()}:{quality_level}"
    return GeneratedProfile(
        profile_id=profile_id,
        printer_id=printer_id,
        material=material,
        quality_level=quality_level,
        settings=settings,
        applied_skills=applied_skill_names,
    )


__all__ = [
    "GeneratedProfile",
    "QUALITY_PRESETS",
    "QualityPreset",
    "generate_profile",
]
