/**
 * Proof tab — live proof bundles from `GET /api/proof/bundles`.
 *
 * Each bundle entry shows id/sha256/branch/commit/files_count/verdict and a
 * per-layer gate matrix. The full Artifacts tab handles per-artifact details;
 * this tab is the "what shipped" ledger for proof bundles only.
 */

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Circle, RefreshCw, X as XIcon, Minus } from "lucide-react";
import { adapters } from "../api/adapters";
import type { GateResult, GateVerdict, ProofBundle, ProofVerdict } from "../types/proof";

const REFRESH_INTERVAL_MS = 30_000;

const VERDICT_CLASS: Record<ProofVerdict, string> = {
  verified: "border-green-700/60 bg-green-950/30 text-green-200",
  pending: "border-amber-700/60 bg-amber-950/30 text-amber-200",
  failed: "border-red-700/60 bg-red-950/30 text-red-200",
};

const GATE_ICON: Record<GateVerdict, JSX.Element> = {
  pass: <CheckCircle2 size={11} className="text-accent-green" />,
  fail: <XIcon size={11} className="text-accent-red" />,
  pending: <Circle size={11} className="text-accent-amber" />,
  skip: <Minus size={11} className="text-muted" />,
};

export function ProofTab() {
  const [bundles, setBundles] = useState<ProofBundle[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const next = await adapters.getProofBundles();
      setBundles(next);
      setError(null);
      if (selectedId == null && next.length > 0) {
        setSelectedId(next[0].id);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load proof bundles.");
    } finally {
      setLoading(false);
    }
  }, [selectedId]);

  useEffect(() => {
    void refresh();
    const t = window.setInterval(() => void refresh(), REFRESH_INTERVAL_MS);
    return () => window.clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const selected = bundles?.find((b) => b.id === selectedId) ?? null;

  return (
    <div data-testid="proof-root" className="flex h-full flex-col gap-3">
      <header className="flex flex-wrap items-center justify-between gap-2 rounded border border-border bg-surface p-3">
        <div>
          <h2 className="text-sm font-semibold text-fg">Proof Bundles</h2>
          <p className="text-xs text-muted">
            Live from <code className="font-mono text-[10px]">GET /api/proof/bundles</code>
            {bundles ? ` · ${bundles.length} returned` : ""}
          </p>
        </div>
        <button
          type="button"
          onClick={() => void refresh()}
          disabled={loading}
          data-testid="proof-refresh"
          className="flex items-center gap-1.5 rounded border border-border px-2 py-1 text-[11px] text-muted hover:border-accent-cyan/40 hover:text-fg disabled:opacity-50"
        >
          <RefreshCw size={11} className={loading ? "animate-spin" : ""} />
          Refresh
        </button>
      </header>

      {error && (
        <div role="alert" data-testid="proof-error" className="rounded border border-red-800/50 bg-red-950/30 p-2 font-mono text-[11px] text-red-200">
          {error}
        </div>
      )}

      {bundles && bundles.length === 0 ? (
        <div
          data-testid="proof-empty"
          className="flex h-full flex-col items-center justify-center rounded border border-border bg-surface p-4 text-center"
        >
          <div className="text-sm font-medium text-fg">No proof bundles</div>
          <div className="mt-1 max-w-md text-xs text-muted">
            GET /api/proof/bundles returned an empty list. Bundles are generated by the truth-gate workflow.
          </div>
        </div>
      ) : (
        <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[420px_1fr]">
          <section className="flex min-h-0 flex-col rounded border border-border bg-surface p-3">
            <h3 className="text-xs font-semibold uppercase text-muted">Bundles</h3>
            <ul className="mt-2 min-h-0 flex-1 space-y-1 overflow-auto">
              {(bundles ?? []).map((b) => {
                const active = b.id === selectedId;
                return (
                  <li key={b.id}>
                    <button
                      type="button"
                      onClick={() => setSelectedId(b.id)}
                      data-testid={`proof-bundle-${b.id}`}
                      className={[
                        "w-full rounded border px-3 py-2 text-left text-xs",
                        active
                          ? "border-accent-blue/60 bg-accent-blue/10"
                          : `${VERDICT_CLASS[b.verdict] ?? VERDICT_CLASS.pending} hover:border-accent-cyan/40`,
                      ].join(" ")}
                    >
                      <div className="flex items-center justify-between gap-2">
                        <span className="truncate font-semibold">{b.id}</span>
                        <span className="rounded bg-bg/40 px-2 py-0.5 font-mono text-[10px] uppercase">
                          {b.verdict}
                        </span>
                      </div>
                      <div className="mt-1 flex flex-wrap items-center gap-2 font-mono text-[10px] text-muted">
                        <span>{b.branch}</span>
                        <span>·</span>
                        <span className="truncate">{b.commit.slice(0, 12)}</span>
                        <span>·</span>
                        <span>{b.files_count} files</span>
                      </div>
                    </button>
                  </li>
                );
              })}
            </ul>
          </section>

          <section
            data-testid="proof-detail"
            className="flex min-h-0 flex-col rounded border border-border bg-surface p-3"
          >
            {selected ? (
              <>
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <h3 className="text-sm font-semibold text-fg">{selected.id}</h3>
                    <p className="font-mono text-[10px] text-muted">{selected.sha256}</p>
                  </div>
                  <span
                    className={`rounded border px-2 py-1 text-[10px] uppercase ${VERDICT_CLASS[selected.verdict] ?? VERDICT_CLASS.pending}`}
                  >
                    {selected.verdict}
                  </span>
                </div>
                <dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-xs sm:grid-cols-4">
                  <Meta label="Branch" value={selected.branch} />
                  <Meta label="Commit" value={selected.commit.slice(0, 12)} mono />
                  <Meta label="Files" value={String(selected.files_count)} />
                  <Meta label="Size" value={`${Math.round(selected.size_bytes / 1024)} kB`} />
                  <Meta label="Timestamp" value={new Date(selected.ts_utc).toLocaleString()} />
                </dl>
                <h4 className="mt-4 text-xs font-semibold uppercase text-muted">Gate matrix</h4>
                <ul className="mt-2 min-h-0 flex-1 space-y-1 overflow-auto">
                  {selected.gates.length === 0 && (
                    <li className="rounded border border-border bg-bg/40 p-2 text-xs text-muted">
                      Bundle has no gate results recorded.
                    </li>
                  )}
                  {selected.gates.map((g, idx) => (
                    <GateRow key={`${g.layer}-${idx}`} gate={g} />
                  ))}
                </ul>
              </>
            ) : (
              <div className="flex h-full items-center justify-center text-xs text-muted">
                Select a bundle on the left.
              </div>
            )}
          </section>
        </div>
      )}
    </div>
  );
}

function Meta({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <>
      <dt className="text-[10px] uppercase text-muted">{label}</dt>
      <dd className={mono ? "font-mono text-fg" : "text-fg"}>{value}</dd>
    </>
  );
}

function GateRow({ gate }: { gate: GateResult }) {
  return (
    <li
      data-testid={`proof-gate`}
      className="flex items-center justify-between gap-2 rounded border border-border bg-bg/40 px-3 py-1.5 text-xs"
    >
      <span className="flex min-w-0 items-center gap-2">
        {GATE_ICON[gate.verdict]}
        <span className="truncate text-fg">{gate.layer}</span>
      </span>
      <span className="shrink-0 flex items-center gap-3 font-mono text-[10px] text-muted">
        <span className="uppercase">{gate.verdict}</span>
        {gate.duration_s != null && <span>{gate.duration_s.toFixed(2)}s</span>}
      </span>
    </li>
  );
}
